### PR TITLE
fix return errors and type errors

### PR DESCRIPTION
**Pull request by akrakman**

### CODE REVIEW

**Review by MinhPhan8803 — COMMENTED** [review]
The `userpage()` function also needs to take username as an argument, to match the url.

**Comment by akrakman** [comment]
Why? What do you want the function to do?

**Comment by MinhPhan8803** [comment]
> Why? What do you want the function to do?

Because otherwise there will be an error when the frontend calls the API.

**Comment by akrakman** [comment]
Does it work when you remove the `<username>` part, meaning it becomes just `/user`? I don't think we need that part in the backend since our routes are determined client-side anyway.

**Comment by MinhPhan8803** [comment]
> 

Havent tried that, lemme try that.

**Comment by MinhPhan8803** [comment]
> Does it work when you remove the `<username>` part, meaning it becomes just `/user`? I don't think we need that part in the backend since our routes are determined client-side anyway.

It works.

**Comment by MinhPhan8803** [comment]
We also want a route in mainpage to determine whether the user is signed in. Currently we have to hardcode the username to the pages which kinda defeat the point of a session.

**Comment by akrakman** [comment]
wdym "hardcode the username to the pages"?

**Comment by akrakman** [comment]
how about that

**Comment by MinhPhan8803** [comment]
> how about that

Looks good.

**Comment by MinhPhan8803** [comment]
> wdym "hardcode the username to the pages"? Do you mean like this https://stackoverflow.com/questions/44031819/access-flask-session-with-reactjs

Previously there was no "legit" way for the frontend to know if the user is logged in, so it is forced to always allow stuff like logout or change user info.

**Review by MinhPhan8803 — APPROVED** [review]

**Pull request merged**
