### PR TITLE
Zfeng13 4

### PR DESCRIPTION
**Pull request by xxxfzxxx**
Main Page Right section works with mock-data in json-server.
Completed:
1. Image Gallery
2. Apartment Info (exclude total upvotes/downvotes)
3. Write Reviews
3. Display Reviews list

Incompleted:
1. show total upvotes/downvotes, because not connected with backend yet
2. Delete a review
3. Edit a review

Plan:
1. Connect the left section with right section

Usage:
start json-server: run "json-server -p 3333 -w db.json" in ./src/frontend

### CODE REVIEW

**Comment by akrakman** [comment]
Am I missing something? Were RightSection and other sections committed?

**Comment by xxxfzxxx** [comment]
To pass the python bulid, I delete flask_cors. But you may want to add it back.
I add flask-cors installation in pylint.

**Comment by MinhPhan8803** [comment]
Delete node_modules from your branch. Also, just curious, why did every file get rewritten?

**Comment by MinhPhan8803** [comment]
> To pass the python bulid, I delete flask_cors. But you may want to add it back.
> I add flask-cors installation in pylint.

Nice

**Comment by akrakman** [comment]
There's too many files. I don't know where they came from but the project is really bloated now.

**Comment by MinhPhan8803** [comment]
> There's too many files. I don't know where they came from but the project is really bloated now. Delete everything you can.

Its from the node_modules folder, which was supposed to be excluded by .gitignore. My guess is that locally that folder lived in the wrong place.

**Comment by xxxfzxxx** [comment]
> > There's too many files. I don't know where they came from but the project is really bloated now. Delete everything you can.
> 
> Its from the `node_modules` folder, which was supposed to be excluded by `.gitignore`. My guess is that locally that folder lived in the wrong place.

removed. sorry about that

**Review by MinhPhan8803 — APPROVED** [review]

**Pull request merged**
