### PR TITLE
tested it works, added data, fix import bug

### PR DESCRIPTION
**Pull request by akrakman**

### CODE REVIEW

**Comment by akrakman** [comment]
@MinhPhan8803

**Review by MinhPhan8803 — APPROVED** [review]
Probably add a couple of users and reviews also.

**Comment by akrakman** [comment]
The apartment data should be an apartment type, right? So no link, and it needs voting?

**Comment by MinhPhan8803** [comment]
> The apartment data should be an apartment type, right? So no link, and it needs voting?

Wdym? The `Apartments` table represent apartments. The `Reviews` represent reviews and must be tied to users. Probably can look at the Zongxian Feng entries for example.

**Comment by MinhPhan8803** [comment]
Yeah, and we are not using apartment links rn, can just ignore that.

**Comment by akrakman** [comment]
For testing, do I use the prod or testing one?

**Comment by MinhPhan8803** [comment]
> For testing, do I use the prod or testing one? The testing didn't have the data

The prod one, the `database_test.db` is reserved for unit tests only.

**Pull request merged**
