### PR TITLE
Pagination, css styling, url, etc.

### PR DESCRIPTION
**Pull request by akrakman**

### CODE REVIEW

**Review by MinhPhan8803 — COMMENTED** [review]
Should try merging from main and testing if it works.

**Comment by akrakman** [comment]
I'm getting errors

**Comment by MinhPhan8803** [comment]
> I'm getting errors

Which kind of errors?

**Comment by akrakman** [comment]
I pulled main and all the changes you made in the PR are staged

**Comment by akrakman** [comment]
Why test?

**Comment by akrakman** [comment]
Yeah I was doing that. I probably shouldn't have deleted them. I think one combination of buttons doesn't result in anything

**Comment by akrakman** [comment]
So I have all of PR 42's changes locally and it's saying to commit. Should I stash it?

**Comment by MinhPhan8803** [comment]
> I have all of PR 42's changes locally and it's saying to commit. Should I stash it?

Wait what is the exact message, does git merge not work?

**Comment by MinhPhan8803** [comment]
https://stackoverflow.com/questions/11646107/you-have-not-concluded-your-merge-merge-head-exists
Try this

> fatal: You have not concluded your merge (MERGE_HEAD exists).
> Please, commit your changes before you merge.

**Comment by MinhPhan8803** [comment]
Worst case just merge this PR and make a new branch to test

**Comment by akrakman** [comment]
Can you approve

**Review by MinhPhan8803 — APPROVED** [review]

**Pull request merged**
